### PR TITLE
Make navbar responsive

### PR DESCRIPTION
**Pull request by ShinhyoBelok**
# Changes 🛠️ 

* Make the navbar responsive for mobile and desktop versions.
* Update house CSS to fix responsiveness.

### CODE REVIEW

**Comment by Vgonma** [comment]
@Gdiazdiaz In the mobile version of delete a house the hamburger button overlaps with the title. Since you worked on this page I wanted to ask you if you could add a margin or padding to the top of the page so it does not overlap.

image

**Comment by Gdiazdiaz** [comment]
> @Gdiazdiaz In the mobile version of delete a house the hamburger button overlaps with the title. Since you worked on this page I wanted to ask you if you could add a margin or padding to the top of the page so it does not overlap.
> 
> image

Hey @Vgonma ! No problem, do you want me to do it in this branch or do you prefer if I open a new one?

**Comment by Vgonma** [comment]
Using this branch is ok

**Comment by Gdiazdiaz** [comment]
Hey @Vgonma The responsive navbar looks amazing!

 

The only thing is that we need to agree on the max for mobile version, I think the initial agreement was 767px, but the current in Navbar is 786 wich causes bug like this

both elements in mobile setup
image

both in desktop setup
image

only the navbar in mobile setup
image

It doesn't matter if we change the setup in Navbar or in the other components but it will be better for the user if we agree on one

[Optional] It will be a great user experience if on the mobile version if, after the user opens the menu and clicks on the link where he wants to go the menu closes itself.

**Review by PrangonGhose — CHANGES_REQUESTED** [review]
Hey @Vgonma and @ShinhyoBelok ,

Great job so far 💚💚💚 The animation looks great. 🥂🥂🥂 But there are some changes that will make the UI more enjoyable.

<h1>Changes Required ♻ </h1>

- As @Gdiazdiaz suggested, it would be better if the navigation panel auto closes itself after going from one page to another.
- When the navigation panel is open, the background page remains usable. Kindly make it either closable if clicked elsewhere on the screen or use background blur to prevent the user from using background pages while the navigation panel is open.

<h3> Optional Suggestions </h3>

- It would be great if the hamburger `=` sign can be transitioned into a ❌sign after opening the navigation panel.
- In the `Main` page, the headings are overlapping with the hamburger sign and also it would be better if the left and right `>` sign can be sized down while in the mobile version to sustain a better look. Kindly take a look at the image below.
image

**Comment by Vgonma** [comment]
@ShinhyoBelok @Gdiazdiaz @PrangonGhose I made the following changes. Could you review them, please?

# Changes
- Updated the responsive breakpoint for the navbar to be 767px max.
- Updated reservations page to no longer overlap with the hamburger menu 
image
- After clicking a navbar link the menu closes automatically.
- Main Page:
  - Fixed hamburger menu collision
  - Reduced arrow button size for mobile
  - Fixed bug that wouldn't let you click on the left arrow until the navbar was opened and closed. This no longer happens.
image
- Navbar icon changes to a cross when the menu is opened
image

**Comment by Vgonma** [comment]
@PrangonGhose @ShinhyoBelok I made some changes for you to review.
# changes
- Moved the open and close navbar button on desktop so it doesn't interfere with the layout. 
- The navbar on mobile now closes whenever the user clicks outside of it and it was also open.

**Review by PrangonGhose — CHANGES_REQUESTED** [review]
Hi @Vgonma 👋👋👋

Your changes looks awesome. 👌👌👌 Some key features that are resolved and look great are-
- The navigation panel open and close animation 💚
- The hamburger menu appearing animation on first load in the mobile version 🥂
- The animation for appearing of _Houses_ in the `Main Page` 🏋️‍♂️
- The `Reserve` page in the mobile version looks good 👌
- The _Navigation closing arrow_ in the `Add House` page now has a background 🥂🥂

However there are two small bugs that need your attention before merging into the base branch. Kindly take a look below.

<h1> Changes Required ♻ </h1>

### In the navigation panel of mobile version

| When navigation menu is open in the desktop version | Going into Mobile Version ✅ |
| --------- | --------- |
| image | image |

| When navigation menu is closed in the desktop version | Going into Mobile version ❌(notice the color of the hamburger) |
| -------- | -------- |
| image | image |
| 1st click in this case on the hamburger changes it into a cross ❌ | 2nd click in this case on the cross opens the navigation ❌and displays hamburger |
| image | image |

### In the `Reserve` page
If the screen size lowers that 300 px, the labels of the inputs start hiding. It's better if the labels and the inputs can be shown in two lines.
image

Feel free to reach out if anything mentioned above is not clear.
Happy coding! 💪💪💪

**Comment by Vgonma** [comment]
# Update: 

- Reworked the whole navbar interaction system. 
- Changed desktop navbar to work with inline style to work with classes.
- Removed conflicting classes.
- Renamed some classes to give them a better descriptive name. 
- Added a new Redux slice and actions to keep track of the navbar states.
- Removed obsolete code.

### Video example:

> Note: the right side looks weird because of the recording tool. The webpage works fine.

Recording 2023-05-16 at 12 48 18

**Comment by PrangonGhose** [comment]
Hello @Vgonma,

Your project is complete. 🥂🥂🥂 It's time to merge it. 

<h1>Approved 🟢</h1>

**Pull request merged**
